MODEL:

  BACKBONE:

    NAME: 'HomoNet'

    VARIANT: 'OneLine'

    IMAGE_SIZE: 128

    RESNET_BLOCK: 'ResNet34'

    PRETRAINED_RESNET: True

    IMAGE_KEY: ['image']

    PATCH_KEYS: ['patch_1', 'patch_2']

    TARGET_KEYS: ['pf_hat_12']

  HEAD:

    NAME: 'RecurrentHead'

    TARGET_GEN: 'all_points'

    LEARNING_KEYS: ['target', 'pfs_hat_12', 'delta', 'pf_hat_12']

DATA:

  # Name of used dataset
  NAME: 'coco'

  # Dataset and camera models root
  DATASET_ROOT: '/home/junchi/sp1/dataset/ImageRegistration/coco'

  # Train/test split csv files
  TEST_SPLIT: '/home/junchi/sp1/dataset/ImageRegistration/coco/val2017'
  TRAIN_SPLIT: '/home/junchi/sp1/dataset/ImageRegistration/coco/train2017'

  # Data transforms & args
  TRANSFORMS: [HomographyNetPrep: [32, 128, ['image_1', 'image_2'], 0, 'all_points'],
               DictToGrayscale: [['patch_1', 'patch_2']],
               DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
               DictToTensor: [['patch_1', 'patch_2', 'target']]]

  TEST_TRANSFORM: [HomographyNetPrep: [32, 128, ['image_1', 'image_2'], 0, 'all_points'],
                   DictToGrayscale: [['patch_1', 'patch_2']],
                   DictStandardize: [[0.443], [0.129], ['patch_1', 'patch_2']],
                   DictToTensor: [['patch_1', 'patch_2', 'target']]]


  # Num workers
  NUM_WORKERS: 8

  # SAMPLER PART
  SAMPLER:

    # Number of images in the batch
    BATCH_SIZE: 4

    # How many images we would call one epoch
    TRAIN_SAMPLES_PER_EPOCH: 230400  # 3600 steps for batch_size=64

    # How many images we would call one epoch
    TEST_SAMPLES_PER_EPOCH: 2304  # 36 steps for batch_size=64

    # Test seed to make the test more comparable
    TRAIN_SEED: 42

    # Test seed to make the test more comparable
    TEST_SEED: 42

SOLVER:

  DEVICE: 'cuda'

  OPTIMIZER: 'Adam'
  MOMENTUM_1: 0.9
  MOMENTUM_2: 0.999

  # This lr worked best for us
  LR: 0.001

  # Equal to 90k steps (LR dropped every 30k steps)
  NUM_EPOCHS: 25

  # Milestones are taken from DeTone paper
  # Learning should be done for 90k iterations, which is 5.7M images
  MILESTONES: [30000, 60000, 90000]
  LR_DECAY: 0.1

  # Original setting from the DeTone paper
  LOSS: 'SequenceLoss'

LOGGING:

  DIR: 'log/junchi-orig-scoco-lr-1e-3'
  STEP: 100
  VERBOSE: False

